[workspace]
members = [
    "exercises/*/*",
    "exercises/08_macros/01_no_op_macro/macros01",
    "exercises/08_macros/02_test/macros02",
    "exercises/08_macros/03_hooks/macros03",
    "ctr",
    "db_launcher"
]
resolver = "2"

[workspace.dependencies]
googletest = "0.11.0"
maplit = "1"
insta = "1.34"
serde_json = "1.0.111"
reqwest = { version = "0.11", features = ["json"] }
tempfile = "3.9.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "migrate"] }
tokio = { version = "1", features = ["full"] }
mockall = { version = "0.12.1" }
wiremock = "0.6.0-rc.3"
syn = "2"
proc-macro2 = "1.0.76"
quote = "1.0.35"
libtest-mimic = "0.7.0"
